// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD0wIYHU49uU7UC7PWUSID98t5a1Ddto8',
    appId: '1:98191629307:web:783c7fa8d4d259b4a0c95e',
    messagingSenderId: '98191629307',
    projectId: 'fir-flutter-codelab-30c46',
    authDomain: 'fir-flutter-codelab-30c46.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-30c46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KgveahWIXsLTW8yuU6mdjeA0Me86_TA',
    appId: '1:98191629307:android:4829770437c4028ba0c95e',
    messagingSenderId: '98191629307',
    projectId: 'fir-flutter-codelab-30c46',
    storageBucket: 'fir-flutter-codelab-30c46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8q-GneBdcbplJSv4UafGXlqtfbIF6ng',
    appId: '1:98191629307:ios:d7262ba8994c93e1a0c95e',
    messagingSenderId: '98191629307',
    projectId: 'fir-flutter-codelab-30c46',
    storageBucket: 'fir-flutter-codelab-30c46.appspot.com',
    iosClientId: '98191629307-o1thldlta577p0397pa6kraia6enh2h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_8q-GneBdcbplJSv4UafGXlqtfbIF6ng',
    appId: '1:98191629307:ios:d7262ba8994c93e1a0c95e',
    messagingSenderId: '98191629307',
    projectId: 'fir-flutter-codelab-30c46',
    storageBucket: 'fir-flutter-codelab-30c46.appspot.com',
    iosClientId: '98191629307-o1thldlta577p0397pa6kraia6enh2h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
